name: orario_gobetti
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: "0.5.12+4"
  webview_flutter: ^1.0.7
  web_scraper: ^0.0.8
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  url_launcher: ^5.7.10
  flutter_launcher_icons: ^0.8.1
  cupertino_icons: ^1.0.0

flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/logo-710-710.png"
  image_path_ios: "assets/images/logo-710-710.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
